# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: yutil
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=amplia-iiot
release:
  prerelease: auto
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    files:
      - LICENSE*
      - README*.md
      - CHANGELOG*.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Env.YUTIL_NEXT }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
- homepage:  https://github.com/amplia-iiot/yutil
  description: Common functionality for working with YAML files
  maintainer: Adrian Haasler Garcia <adrian.haasler@amplia.es>
  license: MIT
  vendor: Amplia Soluciones, S.L.
  formats:
  - apk
  - deb
  - rpm
  replacements:
    linux: Linux
    amd64: x86_64
